workspace:
  base: /go
pipeline:
  build:
    image: golang
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps vet build
  docker:
    image: docker
    repo: majest/drone-rancher
    tag: latest
    when:
      branch: master
