workspace:
  base: /go
pipeline:
  build:
    image: golang
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps vet build
  docker:
    image: plugins/docker
    repo: majest/drone-rancher
    tags:
      - latest
      - 1.0.1
    when:
      branch: master
  docker:
    image: plugins/docker
    repo: majest/drone-rancher
    tags:
      - dev
    when:
      branch: dev
